#!/usr/bin/env bash
# Embernet CODESYS Control — operator one-shot installer.
#
# What it does:
#   1. Preflight: check podman version + systemctl present.
#   2. Pull the pre-built ARM64 image from ghcr (built by .github/
#      workflows/build.yml on every push to main). Falls back to a
#      local `podman build` if the pull fails (offline appliance,
#      missing ghcr auth, unreleased branch).
#   3. Place Quadlet units in /etc/containers/systemd/.
#   4. systemctl daemon-reload && start the service.
#
# Run as root. Re-runnable. Idempotent.
#
# Environment overrides:
#   IMAGE_TAG        (default: latest)
#   CODESYS_VERSION  (default: 4.20.0.0)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

ETC_QUADLET=/etc/containers/systemd
LOG=/var/log/embernet-codesys-install.log

IMAGE_TAG="${IMAGE_TAG:-latest}"
CODESYS_VERSION="${CODESYS_VERSION:-4.20.0.0}"
REGISTRY_IMAGE="${REGISTRY_IMAGE:-ghcr.io/embernet-ai/codesys-linux-arm-64:${IMAGE_TAG}}"

log() { echo "[install] $*" | tee -a "$LOG"; }
die() { echo "[install] ERROR: $*" | tee -a "$LOG" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "Must be run as root (sudo)"
mkdir -p "$(dirname "$LOG")" && : > "$LOG"

log "=== Embernet CODESYS Control installer ==="
log "Repo:            $REPO_ROOT"
log "Image:           $REGISTRY_IMAGE"
log "CODESYS version: $CODESYS_VERSION"

# === Preflight ===
log "Preflight: checking host podman + systemctl"

command -v podman >/dev/null 2>&1 || die "podman not found in PATH"
PODMAN_VER=$(podman --version | awk '{print $3}')
log "  podman:  $PODMAN_VER  OK"

command -v systemctl >/dev/null 2>&1 || die "systemctl not found (this installer requires systemd + Quadlet)"

# Quadlet was introduced in podman 4.4
PODMAN_MAJ=$(echo "$PODMAN_VER" | cut -d. -f1)
PODMAN_MIN=$(echo "$PODMAN_VER" | cut -d. -f2)
if [ "$PODMAN_MAJ" -lt 4 ] || { [ "$PODMAN_MAJ" -eq 4 ] && [ "$PODMAN_MIN" -lt 4 ]; }; then
    die "podman $PODMAN_VER is too old (need 4.4+ for Quadlet support)"
fi

# === Step 1: provision the image ===
#
# Strategy: pull the pre-built image from ghcr (built and pushed by
# .github/workflows/build.yml on every push to main). Fall back to a
# local `podman build` if the pull fails — typically offline appliance,
# missing ghcr auth, or testing an unreleased branch.
provision_image() {
    log "Attempting registry pull: $REGISTRY_IMAGE"
    if podman pull "$REGISTRY_IMAGE" 2>&1 | tee -a "$LOG"; then
        log "Pulled $REGISTRY_IMAGE"
        return 0
    fi
    log "Registry pull failed — falling back to local build"

    HOST_ARCH=$(uname -m)
    case "$HOST_ARCH" in
        aarch64)
            PODMAN_PLATFORM="linux/arm64"
            ;;
        x86_64)
            die "Local build requested on x86_64 host — this image is aarch64-only. Use QEMU emulation via build-multiarch.sh in CI for cross-builds."
            ;;
        *)
            die "Unsupported host architecture: $HOST_ARCH"
            ;;
    esac

    log "Building $REGISTRY_IMAGE locally (single-arch=$PODMAN_PLATFORM)"
    podman build \
        --platform "$PODMAN_PLATFORM" \
        --build-arg CODESYS_VERSION="$CODESYS_VERSION" \
        -t "$REGISTRY_IMAGE" \
        -f "$REPO_ROOT/Containerfile" \
        "$REPO_ROOT" 2>&1 | tee -a "$LOG"
}

provision_image

# === Step 2: place Quadlet units ===
log "Installing Quadlet units to $ETC_QUADLET"
mkdir -p "$ETC_QUADLET"
install -m 644 "$REPO_ROOT/quadlet/embernet-codesys.container"        "$ETC_QUADLET/embernet-codesys.container"
install -m 644 "$REPO_ROOT/quadlet/embernet-codesys-config.volume"    "$ETC_QUADLET/embernet-codesys-config.volume"
install -m 644 "$REPO_ROOT/quadlet/embernet-codesys-data.volume"      "$ETC_QUADLET/embernet-codesys-data.volume"

# === Step 3: activate ===
#
# embernet-codesys.service is GENERATED by Quadlet from the .container
# file at boot. Generated units live under /run/systemd/generator/ and
# cannot be `systemctl enable`d — that errors with
# "transient or generated". Boot-time activation is handled by the
# [Install] section IN the .container file (Quadlet propagates
# WantedBy=multi-user.target automatically). Use `systemctl restart`
# (not start) so install.sh re-runs pick up image bumps and config
# changes — restart is universally safe (starts a stopped unit, restarts
# a running one).
log "Reloading systemd and (re)starting embernet-codesys.service"
systemctl daemon-reload
systemctl restart embernet-codesys.service

# Brief status snapshot
sleep 3
log "=== Service status ==="
systemctl --no-pager --lines=10 status embernet-codesys.service 2>&1 | tee -a "$LOG" || true

log "=== Install complete ==="
log "Next steps:"
log "  - Connect CODESYS IDE to <pi-ip>:1217 (gateway)"
log "  - Browse OPC-UA at  <pi-ip>:4840"
log "  - Web visualization at https://<pi-ip>:8080"
log "  - View logs:        journalctl -u embernet-codesys.service -f"
log "  - Demo mode:        runtime cycles every 30 minutes until a"
log "                      CodeMeter license is provisioned"
